CREATE TABLE milestones (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deadline DATE NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  in_progress BOOLEAN DEFAULT FALSE,
  parent_roadmap INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_roadmap) REFERENCES roadmaps(id) ON DELETE CASCADE
);

